2022_08_02/config/routes.rb
Rails.application.routes.draw do
  root to: 'gossip#index'
  get '/home', to: 'gossip#index'
  get '/team', to: 'team#index'
  get '/contact', to: 'contact#index'
  get '/welcome/:first_name', to: 'welcome#index'
  resources :user
  resources :gossip do
    resources :comment
  end
end

2022_08_02/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

2022_08_02/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content, presence: true
end

2022_08_02/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, presence: true, length: { minimum: 3, maximum: 14 }
  validates :content, presence: true
end

2022_08_02/app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  validates :first_name, presence: true
  validates :last_name, presence: true
end

2022_08_02/app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index; end

  def create; end

  def new; end

  def edit; end

  def show; end

  def update; end

  def destroy; end
end

2022_08_02/app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index

  end

end

2022_08_02/app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def create
    @gossips = Gossip.all
    @gossip = Gossip.new(user: User.first, title: params['gossip_title'], content: params['gossip_content'])
    if @gossip.save
      @posted = true
      render gossip: 'index'
    else
      render new_gossip_path
    end
  end

  def new
    @gossips = Gossip.all
    @gossip = Gossip.new
  end

  def edit; end

  def show
    @gossip = Gossip.find_by_id(params[:id])
  end

  def update; end

  def destroy; end
end

2022_08_02/app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index

  end
end

2022_08_02/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.new
  end

  def new; end

  def edit; end

  def show
    @user = User.find_by_id(params[:id])
  end

  def update; end

  def destroy; end
end

2022_08_02/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @name = params[:first_name]
  end

end

2022_08_02/app/helpers/contact_helper.rb
module ContactHelper
end

2022_08_02/app/helpers/team_helper.rb
module TeamHelper
end

2022_08_02/app/helpers/welcome_helper.rb
module WelcomeHelper
end

2022_08_02/app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

2022_08_02/app/views/comment/destroy.html.erb
<h1>Comment#destroy</h1>
<p>Find me in app/views/comment/destroy.html.erb</p>

2022_08_02/app/views/comment/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

2022_08_02/app/views/comment/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

2022_08_02/app/views/comment/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>

2022_08_02/app/views/comment/show.html.erb
<h1>Comment#show</h1>
<p>Find me in app/views/comment/show.html.erb</p>

2022_08_02/app/views/comment/update.html.erb
<h1>Comment#update</h1>
<p>Find me in app/views/comment/update.html.erb</p>

2022_08_02/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application',
    'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap',
    media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <a class="tmp-a" href="/"><img src="/TMP.png" alt=""></a>
      <nav>
        <ul>
          <li>
            <div><%= link_to "Home", home_path %></div>
          </li>
          <li>
            <div><%= link_to "Team", team_path %></div>
          </li>
          <li>
            <div><%= link_to "Contact", contact_path %></div>
          </li>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

2022_08_02/app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

2022_08_02/app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

2022_08_02/app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

2022_08_02/app/views/user/index.html.erb
<div class="container text-center">
  <h1 class="mb-3">Users</h1>
  <div class="row row-cols-1 row-cols-md-3 text-center">
    <% @users.each_with_index do |user| %>
      <div class="col">
        <div class="col card mb-4 rounded-3 shadow-sm">
          <div class="card-header">
            <a class="index" href="/user/<%=user.id %>">User ID: <%= user.id %></a>
          </div>
          <div class= "card-body">
            <span class="card-tile ">First name:      </span><%= user.first_name %><br>
            <span class="font-bold">Last Name:      </span><%= user.last_name %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

2022_08_02/app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

2022_08_02/app/views/user/show.html.erb
<div class="container text-center">
    <div class="card shadow-sm">
        <div class="card-header">
            <a class="index" href="/user/<%=@user.id %>">User n° <%= @user.id %></a>
        </div>
        <div class= "card-body">
            <p>First name: <br><%= @user.first_name %></p><br>
            <p>Last name: <br><%= @user.last_name %></p><br>
            <p>User creation: <br><%= @user.created_at %></p><br>
        </div>
    </div>
</div>

2022_08_02/app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>