2022_08_04/config/routes.rb
Rails.application.routes.draw do
  root to: 'gossip#index'
  get '/home', to: 'gossip#index'
  get '/team', to: 'team#index'
  get '/contact', to: 'contact#index'
  get '/welcome/:first_name', to: 'welcome#index'
  resources :city
  resources :session, only: %i[new create destroy]
  resources :user
  resources :like, only: %i[create destroy]
  resources :gossip do
    resources :comment
  end
end

2022_08_04/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

2022_08_04/app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
  validates :name, presence: true
end

2022_08_04/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content, presence: true
end

2022_08_04/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_one :city, through: :user
  has_many :comments
  has_many :likes
  validates :user, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 14 }
  validates :content, presence: true
end

2022_08_04/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :user, uniqueness: { scope: :gossip }
end

2022_08_04/app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  validates :email, presence: true
  validates :password_digest, presence: true

    # City.find_or_create_by_name(city.name)
  # end
end

2022_08_04/app/controllers/city_controller.rb
class CityController < ApplicationController
  def index; end

  def create; end

  def new; end

  def edit; end

  def show
    puts '##################################################'
    @city = City.where(id: params[:id]).first
    @users = User.where(city_id: params[:id])
    @gossips = Gossip.where(user: @users)
  end

  def update; end

  def destroy; end
end

2022_08_04/app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :authenticate_user, only: %i[create new]

  def index; end

  def create
    @comments = Comment.all
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.new(user: current_user, content: params['comment_content'], gossip_id: params[:gossip_id])
    if @comment.save
      @posted = true
      redirect_to gossip_path(@gossip.id)
    else
      render :new
    end
  end

  def new
    puts params.inspect
    puts params[:id]
    @gossip = Gossip.find_by_id(params[:id])
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def show; end

  def update
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    if @comment.update(content: params[:comment_content])
      @posted = true
      redirect_to gossip_path(@gossip.id)
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(@gossip.id)
  end

  private

  def authenticate_user
    return if current_user

    flash[:alert] = 'Please log in.'
    redirect_to new_session_path
  end
end

2022_08_04/app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index

  end

end

2022_08_04/app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  before_action :authenticate_user, only: %i[new show edit update destroy]

  def index
    @gossips = Gossip.all
    @likes = Like.all
  end

  def create
    @gossips = Gossip.all
    @gossip = Gossip.new(
      title: params[:gossip_title],
      content: params[:gossip_content]
    )
    @gossip.user = User.find_by(id: session[:user_id])
    if @gossip.save
      @posted = true
      render gossip: 'index'
    else
      render new_gossip_path
    end
  end

  def new
    @gossip = Gossip.new
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def show
    @gossip = Gossip.find_by_id(params[:id])
    @comments = Comment.where(gossip_id: params[:id])
    @like_count = Like.where(gossip_id: @gossip.id).count
    @likes = Like.all
  end

  def update
    @gossip = Gossip.find_by_id(params[:id])
    if @gossip.update(
      title: params[:gossip_title],
      content: params[:gossip_content]
    )
      @posted = true
      redirect_to gossip_path(@gossip.id)
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find_by_id(params[:id])
    @gossip.destroy
    flash[:success] = 'The gossip was destroyed'
    redirect_to gossip_index_path
  end

  private

  def authenticate_user
    return if current_user

    flash[:alert] = 'Please log in.'
    redirect_to new_session_path
  end
end

2022_08_04/app/controllers/like_controller.rb
class LikeController < ApplicationController
  def create
    gossip_id = params[:gossip_id].keys[0].to_i
    puts gossip_id
    puts current_user.id
    @like = Like.create(user_id: current_user.id, gossip_id: gossip_id)
    redirect_back(fallback_location: root_path) if @like.save
  end

  def destroy
    gossip_id = params[:gossip_id].keys[0].to_i
    like_id = Like.where(user_id: current_user.id, gossip_id: gossip_id).first.id
    Like.destroy(like_id)
    redirect_back(fallback_location: root_path)
  end
end

2022_08_04/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session_email])

    if user&.authenticate(params[:session_password])
      session[:user_id] = user.id
      @gossips = Gossip.all
      @likes = Like.all
      flash.now[:success] = "Welcome #{user.first_name}. You are now successfully logged in."
      redirect_to :home
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @gossips = Gossip.all
    flash.now[:info] = 'You logged out successfully'
    redirect_to :home
  end
end

2022_08_04/app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index

  end
end

2022_08_04/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation],
      city: City.find_or_create_by(name: params[:city])
    )
    if @user.save
      flash.now[:success] = 'User successfully created!'
      redirect_to home_path
    else
      flash.now[:alert] = 'Invalid email/password combination.'
      render new_user_path
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(
      email: params[:email],
      password: params[:password],
      city: City.find_or_create_by(name: params[:city]),
      first_name: params[:first_name],
      last_name: params[:last_name],
      age: params[:age],
      description: params[:description]
    )
    flash.now[:success] = 'User successfully updated!'
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] =
        @user.errors.full_messages.each { |m| puts m }
      render :edit
    end
  end

  def destroy; end
end

2022_08_04/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @name = params[:first_name]
  end

end

2022_08_04/app/helpers/application_helper.rb
module ApplicationHelper
  # This will assign the correct bootstrap colors to the messages
  def flash_class(name)
    case name
    when 'notice' then 'alert alert-info text-center'
    when 'success' then 'alert alert-success alert-dismissable text-center'
    when 'error', 'alert', 'danger' then 'alert alert-danger alert-dismissable text-center'
    else
      'alert alert-primary'
    end
  end
end

2022_08_04/app/helpers/city_helper.rb
module CityHelper
end

2022_08_04/app/helpers/contact_helper.rb
module ContactHelper
end

2022_08_04/app/helpers/like_helper.rb
module LikeHelper
end

2022_08_04/app/helpers/session_helper.rb
module SessionHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    return false if session[:user_id].class != Integer

    true
  end
end

2022_08_04/app/helpers/team_helper.rb
module TeamHelper
end

2022_08_04/app/helpers/welcome_helper.rb
module WelcomeHelper
end

2022_08_04/app/views/team/index.html.erb
<div class="container text-center">
    <h1 class="mb-3">Development Team</h1><br>
    <p>This website has been provided by:</p>
    <div class="row row-cols-1 row-cols-md-2 text-center ">
      <div class= "col">
        <div class="card">
            <div class="card-header">
                <a href="http://www.github.com/Pefington">Pefington</a>
            </div>
            <div class= "card-body">
                <span class="card-tile">The best front end developer. But he hates Bootstraps</span><br>
            </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
            <div class="card-header">
                <a href="http://www.github.com/Samsou1">Samsou1</a>
            </div>
            <div class= "card-body">
                <span class="card-tile">He likes to have his snacks right at 5pm. But if he does he's an ok developer</span><br>
            </div>
        </div>
      </div>
    </div>
</div>

2022_08_04/app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

2022_08_04/app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

2022_08_04/app/views/user/edit.html.erb
<div class="container text-center">
  <h3>You're new to this gossip world? You're at the right place.</h3>
  <br>
  <%= form_with url: user_path, method: :patch, local: true do |form| %>
    <%#La méthode form_with appelle implicitement la méthode post, local true est nécessaire pour rails 5.2 et 6.0%>
    <p>Email</p>
    <%= form.text_field :email, value: @user.email %>
    <br>
    <p>First name</p>
    <%= form.text_field :first_name, value: @user.first_name %>
    <br>
    <p>Last name</p>
    <%= form.text_field :last_name, value: @user.last_name %>
    <br>
    <p>City</p>
    <%= form.text_field :city, value: @user.city.name %>
    <br>
    <p>Age</p>
    <%= form.text_field :age, value: @user.age %>
    <br>
    <p>Description</p>
    <%= form.text_field :description, value: @user.description %>
    <br>
    <br>
    <p>Password</p>
    <%= form.password_field :password %>
    <br>
    <p>Repeat password</p>
    <%= form.password_field :password_confirmation %>
    <br>
    <%= form.submit "Publish" %>
  <% end %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p>We were not able to edit this comment for the following reason(s):</p>
      <ul style="list-style-type:none">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <br>
    <p>Please try again</p>
  <% end %>
</div>

2022_08_04/app/views/user/index.html.erb
<div class="container text-center">
  <h1 class="mb-3">Users</h1>
  <div class="row row-cols-1 row-cols-md-3 text-center">
    <% @users.each_with_index do |user| %>
      <div class="col">
        <div class="col card mb-4 rounded-3 shadow-sm">
          <div class="card-header">
            <a class="index" href="/user/<%=user.id %>">User ID: <%= user.id %></a>
          </div>
          <div class= "card-body">
            <span class="card-tile ">First name:      </span><%= user.first_name %><br>
            <span class="font-bold">Last Name:      </span><%= user.last_name %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

2022_08_04/app/views/user/new.html.erb
<div class="container text-center">
  <h3>You're new to this gossip world? You're at the right place.</h3>
  <br>
  <%= form_with url: user_index_path, local: true do |form| %>
    <p>First name</p>
    <%= form.text_field :first_name %>
    <br>
    <p>Last name</p>
    <%= form.text_field :last_name %>
    <br>
    <p>City</p>
    <%= form.text_field :city %>
    <br>
    <p>Email</p>
    <%= form.text_field :email %>
    <br>
    <br>
    <p>Password</p>
    <%= form.password_field :password %>
    <br>
    <p>Repeat password</p>
    <%= form.password_field :password_confirmation %>
    <br>
    <%= form.submit "Publish" %>
  <% end %>
  <br>
  <br>
  <% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p>We were not able to create this new user for the following reason(s):</p>
      <ul style="list-style-type:none">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <br>
    <p>Please try again</p>
  <% end %>
</div>

2022_08_04/app/views/user/show.html.erb
<div class="container text-center">
  <div class="card shadow-sm">
    <div class="card-header">
      <a class="index" href="/user/<%=@user.id %>">User n° <%= @user.id %></a>
    </div>
    <div class= "card-body">
      <p>First name: <br>
        <%= @user.first_name %>
      </p>
      <%# <br> %>
      <p>Last name: <br>
        <%= @user.last_name %>
      </p>
      <%# <br> %>
      <p>User creation: <br>
        <%= @user.created_at %>
      </p>
      <%# <br> %>
      <p>City: <br>
        <%= link_to @user.city.name, city_path(@user.city.id) %>
      </p>
      <%# <br> %>
      <p>Description: <br>
        <%= @user.description %>
      </p>
      <%# <br> %>
      <p>Email: <br>
        <%= @user.email %>
      </p>
      <%# <br> %>
      <p>Age: <br>
        <%= @user.age %>
      </p>
      <%# <br> %>
    </div>
    <p>Do you want to edit your profile?</p>
    <div><%= link_to "Click here", edit_user_path(current_user.id) %></div>
  </div>
</div>

2022_08_04/app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>

2022_08_04/app/views/welcome/index.html.erb
<h1 class="font-bold text-center">Hello <%= @name %></h1>